### ISSUE TITLE
Distance to arrival and Tracker Route show up in Watchman Report as Unavailable and Unknown respectively

### ISSUE THREAD

**Issue by rdperkins** [Teslemetry/hass-teslemetry#152]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The garage door opener automation depends on the  distance_to_arrival entity value and Watchman shows it as unavailable. This I'd like fixed. The tracker route I don't care about Except it shows up in the Watchman Report which is annoying. Thanks for your help. The full list of Watchman items related to the Tesla are below in the reproduction steps. Scarlet is the name of my red Tesla :).

### Reproduction steps

1. Set a destination in the Tesla and it didn't change anything.
2. sensor.scarlet_distance_to_arrival [unavail]
3. device_tracker.scarlet_route [unknown]
4. proximity.home_tesla [missing]

**Comment by Bre77** [comment]
Can you please put a destination into your vehicle, wait 30 seconds, then generate a diagnostic and attach it here.

The sensors you're describing are meant to be unavailable when there is no destination, so if you have configured one in your vehicle and they are not working we will need to figure out why.

**Comment by Bre77** [comment]
Its in the three dot menu of the integration page, or on the device info
![image](https://github.com/user-attachments/assets/9127174d-c5ae-4bbd-884d-ee1d046ec91a)

https://www.home-assistant.io/integrations/diagnostics/

**Comment by rdperkins** [comment]
Did you receive the email with the attached diagnostics? I sent it on the 16th.

Robert

**Comment by Bre77** [comment]
> Did you receive the email with the attached diagnostics? I sent it on the 16th.

It does appear to be on the GitHub issue, so I think you'll have to open the issue to attach it. Email seemly doesn't work

**Comment by rdperkins** [comment]
No, I didn't receive your email, but am attaching the diagnostic below.
[config_entry-teslemetry-e7fe7d7557a3d552b23a9d972d5cb3a9.json](https://github.com/user-attachments/files/17880092/config_entry-teslemetry-e7fe7d7557a3d552b23a9d972d5cb3a9.json)
